In this I have Cleaned the First Dataset - Campaign
First Import Required libraries

In [1]:
import pandas as pd
import sqlite3

In [4]:
campaigns = pd.read_csv("campaign_raw.csv")

Head Function will show us top 5 Records from dataset

In [5]:
campaigns.head()

,Data Source name,Date,Campaign Name,Campaign Effective Status,Ad Set Name,Ad Name,Country Funnel,Geo Location Segment,FB Spent Funnel (INR),Amount Spent (INR),...,Checkouts Initiated,Adds of Payment Info,Purchases,Purchases Conversion Value (INR),Website Contacts,Messaging Conversations Started,Adds to Cart Conversion Value (INR),Checkouts Initiated Conversion Value (INR),Adds of Payment Info Conversion Value (INR),Row Count
0,Brand A,02-01-2026,NaN,PAUSED,TOF | LAL 3-5% | Sales | Womens,Custom | Video 2 | EOSS | 15th Dec 25 – Copy,India,India,0.0,0.0,...,-0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,1.0
1,Brand A,03-01-2026,Growify | 11th June | TOF | ABO | INDIA | LAL ...,paused,TOF | LAL 3-5% | Sales | Womens,Custom | Video 2 | EOSS | 15th Dec 25 – Copy,India,India,0.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,1.0
2,NaN,20-01-2026,Growify | 11th June | TOF | ABO | INDIA | LAL ...,PAUSED,NaN,NaN,INDIA,India,0.0,0.0,...,0.0,0.0,0.0,-0.0,NaN,0.0,0.0,0.0,0.0,1.0
3,Brand A,01-01-2026,Growify | 11th June | TOF | ABO | INDIA | LAL ...,NaN,TOF | LAL 3-5% | Sales | Womens,Custom | Video 2 | EOSS | 15th Dec 25 – Copy,India,India,0.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0.0,5964500.0,0.0,0.0,1.0
4,Brand A,11-01-2026,GROWIFY | 11TH JUNE | TOF | ABO | INDIA | LA...,PAUSED,NaN,Custom | Video 2 | EOSS | 15th Dec 25 – Copy,NAN,India,0.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0

In [6]:
campaigns.columns

Index(['Data Source name', 'Date', 'Campaign Name',
       'Campaign Effective Status', 'Ad Set Name', 'Ad Name', 'Country Funnel',
       'Geo Location Segment', 'FB Spent Funnel (INR)', 'Amount Spent (INR)',
       'Clicks (all)', 'Impressions', 'Page Likes', 'Landing Page Views',
       'Link Clicks', 'Adds to Cart', 'Checkouts Initiated',
       'Adds of Payment Info', 'Purchases', 'Purchases Conversion Value (INR)',
       'Website Contacts', 'Messaging Conversations Started',
       'Adds to Cart Conversion Value (INR)',
       'Checkouts Initiated Conversion Value (INR)',
       'Adds of Payment Info Conversion Value (INR)', 'Row Count'],
      dtype='object')

In [7]:
campaigns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10028 entries, 0 to 10027
Data columns (total 26 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Data Source name                             9399 non-null   object
 1   Date                                         9395 non-null   object
 2   Campaign Name                                9392 non-null   object
 3   Campaign Effective Status                    9383 non-null   object
 4   Ad Set Name                                  9387 non-null   object
 5   Ad Name                                      9382 non-null   object
 6   Country Funnel                               9232 non-null   object
 7   Geo Location Segment                         9360 non-null   object
 8   FB Spent Funnel (INR)                        9278 non-null   float64
 9   Amount Spent (INR)                           9358 non-null   float64
 10  Clicks (all)                                 9362 non-null   float64
 11  Impressions                                  9360 non-null   float64
 12  Page Likes                                   9122 non-null   float64
 13  Landing Page Views                           9359 non-null   float64
 14  Link Clicks                                  9356 non-null   float64
 15  Adds to Cart                                 9369 non-null   float64
 16  Checkouts Initiated                          8983 non-null   float64
 17  Adds of Payment Info                         8950 non-null   float64
 18  Purchases                                    9355 non-null   float64
 19  Purchases Conversion Value (INR)             9358 non-null   float64
 20  Website Contacts                             7455 non-null   float64
 21  Messaging Conversations Started              9364 non-null   float64
 22  Adds to Cart Conversion Value (INR)          9366 non-null   float64
 23  Checkouts Initiated Conversion Value (INR)   8402 non-null   float64
 24  Adds of Payment Info Conversion Value (INR)  8936 non-null   float64
 25  Row Count                                    9350 non-null   float64
dtypes: float64(18), object(8)
memory usage: 2.0+ MB

In [8]:
campaigns.describe()

,FB Spent Funnel (INR),Amount Spent (INR),Clicks (all),Impressions,Page Likes,Landing Page Views,Link Clicks,Adds to Cart,Checkouts Initiated,Adds of Payment Info,Purchases,Purchases Conversion Value (INR),Website Contacts,Messaging Conversations Started,Adds to Cart Conversion Value (INR),Checkouts Initiated Conversion Value (INR),Adds of Payment Info Conversion Value (INR),Row Count
count,9278.000000,9358.000000,9.362000e+03,9.360000e+03,9122.000000,9.359000e+03,9356.000000,9369.000000,8983.000000,8950.000000,9355.000000,9.358000e+03,7455.000000,9364.000000,9.366000e+03,8.402000e+03,8.936000e+03,9350.000000
mean,6355.360368,10022.984526,1.778205e+03,1.092893e+05,0.414383,1.692459e+03,1303.923685,24.496318,1.476567,0.301006,0.997221,6.688348e+04,1.486653,5.787804,6.058349e+05,1.864319e+05,5.582583e+04,6.501497
std,39004.957048,59852.497035,6.702752e+04,1.777644e+06,6.288479,4.389078e+04,20862.287250,236.753517,19.153097,7.962555,13.590950,1.042466e+06,22.117744,56.556824,6.341608e+06,3.082780e+06,1.359560e+06,19.715658
min,-312112.320000,-957413.990000,-3.255600e+06,-3.639065e+06,-77.000000,-3.256500e+04,-30780.000000,-594.000000,-390.000000,-168.000000,-164.000000,-2.552301e+07,-64.000000,-567.000000,-6.226054e+07,-1.092500e+07,-3.010700e+07,-66.000000
25%,28.690000,26.532384,1.000000e+00,4.400000e+01,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
50%,304.870000,300.380000,1.900000e+01,4.010000e+02,0.000000,6.000000e+00,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
75%,1122.520000,1121.392500,9.000000e+01,2.153500e+03,0.000000,5.300000e+01,68.000000,1.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
max,957356.160000,964131.980000,4.164600e+06,7.734387e+07,154.000000,3.795090e+06,935388.000000,7326.000000,936.000000,392.000000,492.000000,2.552301e+07,832.000000,1512.000000,1.706904e+08,1.230960e+08,5.236000e+07,132.000000

Calculated the sum of duplicate rows

In [9]:
campaigns.duplicated().sum()

310

Delete Duplicate Rows

In [21]:
campaigns = campaigns.drop_duplicates()

In [22]:
campaigns.duplicated().sum()

0

Here I changed the DataType of Date Column

In [14]:
campaigns["Date"] = pd.to_datetime(campaigns["Date"], dayfirst=True, errors="coerce")
campaigns["Date"].dtype

dtype('<M8[ns]')

Calculated the Null values in each Column

In [15]:
campaigns.isnull().sum()

Data Source name                                612
Date                                           1054
Campaign Name                                   621
Campaign Effective Status                       620
Ad Set Name                                     614
Ad Name                                         620
Country Funnel                                  765
Geo Location Segment                            635
FB Spent Funnel (INR)                           725
Amount Spent (INR)                              643
Clicks (all)                                    638
Impressions                                     650
Page Likes                                      884
Landing Page Views                              648
Link Clicks                                     654
Adds to Cart                                    631
Checkouts Initiated                            1013
Adds of Payment Info                           1042
Purchases                                       658
Purchases Conversion Value (INR)                648
Website Contacts                               2500
Messaging Conversations Started                 644
Adds to Cart Conversion Value (INR)             645
Checkouts Initiated Conversion Value (INR)     1580
Adds of Payment Info Conversion Value (INR)    1065
Row Count                                       652
dtype: int64

It looks through the DataFrame (campaigns) and picks out columns with the data type object.
It searches for any NaN (Not a Number) or None values within those specific columns. These represent empty cells or missing information.
It swaps those empty spots with the string "Unknown" and saves the changes back into the original DataFrame.

In [17]:
text_cols = campaigns.select_dtypes(include='object').columns
campaigns[text_cols] = campaigns[text_cols].fillna("Unknown")

In [18]:
num_cols = campaigns.select_dtypes(include=['int64','float64']).columns
campaigns[num_cols] = campaigns[num_cols].fillna(0)

Rechecked the null values

In [19]:
campaigns.isnull().sum()

Data Source name                                  0
Date                                           1054
Campaign Name                                     0
Campaign Effective Status                         0
Ad Set Name                                       0
Ad Name                                           0
Country Funnel                                    0
Geo Location Segment                              0
FB Spent Funnel (INR)                             0
Amount Spent (INR)                                0
Clicks (all)                                      0
Impressions                                       0
Page Likes                                        0
Landing Page Views                                0
Link Clicks                                       0
Adds to Cart                                      0
Checkouts Initiated                               0
Adds of Payment Info                              0
Purchases                                         0
Purchases Conversion Value (INR)                  0
Website Contacts                                  0
Messaging Conversations Started                   0
Adds to Cart Conversion Value (INR)               0
Checkouts Initiated Conversion Value (INR)        0
Adds of Payment Info Conversion Value (INR)       0
Row Count                                         0
dtype: int64

Here I Filled the Date Column Missing Values with Forward Fill

In [25]:
campaigns['Date'] = campaigns['Date'].ffill()

In [26]:
campaigns.isnull().sum()

Data Source name                               0
Date                                           0
Campaign Name                                  0
Campaign Effective Status                      0
Ad Set Name                                    0
Ad Name                                        0
Country Funnel                                 0
Geo Location Segment                           0
FB Spent Funnel (INR)                          0
Amount Spent (INR)                             0
Clicks (all)                                   0
Impressions                                    0
Page Likes                                     0
Landing Page Views                             0
Link Clicks                                    0
Adds to Cart                                   0
Checkouts Initiated                            0
Adds of Payment Info                           0
Purchases                                      0
Purchases Conversion Value (INR)               0
Website Contacts                               0
Messaging Conversations Started                0
Adds to Cart Conversion Value (INR)            0
Checkouts Initiated Conversion Value (INR)     0
Adds of Payment Info Conversion Value (INR)    0
Row Count                                      0
dtype: int64

In [ ]:
Normalize the Data

In [27]:
campaigns['Campaign Effective Status'] = campaigns['Campaign Effective Status'].str.upper()

In [30]:
campaigns["Campaign Effective Status"].dtype

dtype('O')

In [33]:
campaigns['Campaign Effective Status'].unique()

array(['PAUSED', 'UNKNOWN', 'ACTIVE', 'NAN'], dtype=object)

In [32]:
campaigns['Campaign Effective Status'] = campaigns['Campaign Effective Status'].str.strip()

In [34]:
import numpy as np
campaigns['Campaign Effective Status'] = campaigns['Campaign Effective Status'].replace("NAN", np.nan)

In [35]:
campaigns['Campaign Effective Status'] = campaigns['Campaign Effective Status'].fillna("UNKNOWN")

In [36]:
campaigns['Campaign Effective Status'].unique()

array(['PAUSED', 'UNKNOWN', 'ACTIVE'], dtype=object)

Again checked for Duplicated values because sometimes normalizing can create duplicate Value

In [37]:
campaigns.duplicated().sum()

76

In [38]:
campaigns[campaigns.duplicated()]

,Data Source name,Date,Campaign Name,Campaign Effective Status,Ad Set Name,Ad Name,Country Funnel,Geo Location Segment,FB Spent Funnel (INR),Amount Spent (INR),...,Checkouts Initiated,Adds of Payment Info,Purchases,Purchases Conversion Value (INR),Website Contacts,Messaging Conversations Started,Adds to Cart Conversion Value (INR),Checkouts Initiated Conversion Value (INR),Adds of Payment Info Conversion Value (INR),Row Count
1174,Brand A,2026-02-17,Growify | TOF | Conversion | India,ACTIVE,Ecomm | Travel,Video | esha | – Copy,India,India,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,1.0
2784,Brand B,2026-02-17,Growify | TOF | Conversion | US,ACTIVE,Ecomm | Latest Fashion,Unknown,United States,USA,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,1.0
8025,Brand B,2026-01-09,Growify | TOF | Traffic-ThruPlay | India,PAUSED,Ecomm | Women Clothing,Custom_Video_CampaignShoot_Lehenga_Mehfil,India,India,0.03,4.53,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,1.0
8026,Brand B,2026-01-05,Growify | TOF | Conversion | UAE,PAUSED,Ecomm | Magazines,Custom | Carousel | CLP | Fanah | BAU | Full P...,United Kingdom,Rest of the World,206.75,206.75,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8029,Brand B,2026-01-26,Growify | Retarget | Conversion | AUS+CAN+UK+USA,ACTIVE,Ecomm | Retargeting,Custom | SIngle Video | PLP | Fitoor BAU – Copy,United Kingdom,Unknown,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9887,Brand B,2026-01-05,Growify | 3 July 2025 | US/CA/AUS | Engagement,PAUSED,TOF | Shopify Data Lookalike | US/CA/AUS | Wha...,Custom | Carousel | Message | Celeb Content | ...,United States,USA,485.14,485.14,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,1.0
9890,Brand B,2026-01-26,Growify | MOF+BOF | Mehfil+Fitoor+Mahiya | Leh...,ACTIVE,Ecomm | CX Data,Custom | Single Video | PLP | Fitoor | BAU – Copy,Canada,Rest of the World,0.00,0.00,...,0.0,-0.0,0.0,-0.0,0.0,0.0,0.0,0.0,0.0,1.0
9910,Brand A,2026-01-30,Growify | 24th Jan 26 | Tof | Sales | India,PAUSED,TOF | INDIA | WOMEN | Maximum value of Convers...,Video | esha |,India,India,895.44,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,65800.0,0.0,0.0,1.0
10023,Brand A,2026-01-01,Growify | TOF | Conversion | India,ACTIVE,TOF | INDIA | IOS,Catalogue | All Product | Instock,India,Unknown,1157.77,1157.77,...,0.0,0.0,0.0,0.0,0.0,0.0,33406.0,0.0,0.0,0.0
10026,Brand A,2026-01-02,Growify | 9th October 25 | MOF | Sales | Women,PAUSED,MOF | Whtsapp CD | Sales - Women,Custom | Video 1 | EOSS | 15th Dec 25 – Copy,INDIA,India,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,1.0

In [39]:
campaigns = campaigns.drop_duplicates()

In [40]:
campaigns.duplicated().sum()

0

CTR

In [43]:
campaigns.loc[:, 'CTR'] = campaigns['Clicks (all)'] / campaigns['Impressions']

In [44]:
campaigns[['Clicks (all)', 'Impressions', 'CTR']].head()

   Clicks (all)  Impressions  CTR
0           0.0          0.0  NaN
1           0.0          0.0  NaN
2           0.0          0.0  NaN
3          -0.0          0.0  NaN
4           0.0          0.0  NaN

CPM

In [47]:
campaigns.loc[:, 'CPM'] = (campaigns['Amount Spent (INR)'] / campaigns['Impressions']) * 1000
campaigns.loc[campaigns['Impressions'] == 0, 'CPM'] = 0

In [49]:
campaigns[['CTR','CPM']].head()

   CTR  CPM
0  NaN  0.0
1  NaN  0.0
2  NaN  0.0
3  NaN  0.0
4  NaN  0.0

ROI

In [52]:
campaigns.loc[:, 'ROI'] = (
    campaigns['Purchases Conversion Value (INR)'] - campaigns['Amount Spent (INR)']
) / campaigns['Amount Spent (INR)']

campaigns.loc[campaigns['Amount Spent (INR)'] == 0, 'ROI'] = 0

CPC

In [53]:
campaigns.loc[:, 'CPC'] = campaigns['Amount Spent (INR)'] / campaigns['Clicks (all)']
campaigns.loc[campaigns['Clicks (all)'] == 0, 'CPC'] = 0

In [54]:
campaigns[['CTR','CPC','CPM','ROI']].head()

   CTR  CPC  CPM  ROI
0  NaN  0.0  0.0  0.0
1  NaN  0.0  0.0  0.0
2  NaN  0.0  0.0  0.0
3  NaN  0.0  0.0  0.0
4  NaN  0.0  0.0  0.0

In [55]:
text_cols = campaigns.select_dtypes(include='object').columns
text_cols

Index(['Data Source name', 'Campaign Name', 'Campaign Effective Status',
       'Ad Set Name', 'Ad Name', 'Country Funnel', 'Geo Location Segment'],
      dtype='object')

In [56]:
campaigns[text_cols] = campaigns[text_cols].apply(lambda x: x.str.strip().str.upper())

In [57]:
campaigns[text_cols] = campaigns[text_cols].fillna("UNKNOWN")

In [59]:
campaigns.head()

,Data Source name,Date,Campaign Name,Campaign Effective Status,Ad Set Name,Ad Name,Country Funnel,Geo Location Segment,FB Spent Funnel (INR),Amount Spent (INR),...,Website Contacts,Messaging Conversations Started,Adds to Cart Conversion Value (INR),Checkouts Initiated Conversion Value (INR),Adds of Payment Info Conversion Value (INR),Row Count,CTR,CPM,ROI,CPC
0,BRAND A,2026-01-02,UNKNOWN,PAUSED,TOF | LAL 3-5% | SALES | WOMENS,CUSTOM | VIDEO 2 | EOSS | 15TH DEC 25 – COPY,INDIA,INDIA,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0
1,BRAND A,2026-01-03,GROWIFY | 11TH JUNE | TOF | ABO | INDIA | LAL ...,PAUSED,TOF | LAL 3-5% | SALES | WOMENS,CUSTOM | VIDEO 2 | EOSS | 15TH DEC 25 – COPY,INDIA,INDIA,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0
2,UNKNOWN,2026-01-20,GROWIFY | 11TH JUNE | TOF | ABO | INDIA | LAL ...,PAUSED,UNKNOWN,UNKNOWN,INDIA,INDIA,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0
3,BRAND A,2026-01-01,GROWIFY | 11TH JUNE | TOF | ABO | INDIA | LAL ...,UNKNOWN,TOF | LAL 3-5% | SALES | WOMENS,CUSTOM | VIDEO 2 | EOSS | 15TH DEC 25 – COPY,INDIA,INDIA,0.0,0.0,...,0.0,0.0,5964500.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0
4,BRAND A,2026-01-11,GROWIFY | 11TH JUNE | TOF | ABO | INDIA | LAL ...,PAUSED,UNKNOWN,CUSTOM | VIDEO 2 | EOSS | 15TH DEC 25 – COPY,NAN,INDIA,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0

In [60]:
campaigns.isnull().sum()

Data Source name                                 0
Date                                             0
Campaign Name                                    0
Campaign Effective Status                        0
Ad Set Name                                      0
Ad Name                                          0
Country Funnel                                   0
Geo Location Segment                             0
FB Spent Funnel (INR)                            0
Amount Spent (INR)                               0
Clicks (all)                                     0
Impressions                                      0
Page Likes                                       0
Landing Page Views                               0
Link Clicks                                      0
Adds to Cart                                     0
Checkouts Initiated                              0
Adds of Payment Info                             0
Purchases                                        0
Purchases Conversion Value (INR)                 0
Website Contacts                                 0
Messaging Conversations Started                  0
Adds to Cart Conversion Value (INR)              0
Checkouts Initiated Conversion Value (INR)       0
Adds of Payment Info Conversion Value (INR)      0
Row Count                                        0
CTR                                            966
CPM                                              0
ROI                                              0
CPC                                              0
dtype: int64

In [61]:
campaigns.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9637 entries, 0 to 10025
Data columns (total 30 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Data Source name                             9637 non-null   object
 1   Date                                         9637 non-null   datetime64[ns]
 2   Campaign Name                                9637 non-null   object
 3   Campaign Effective Status                    9637 non-null   object
 4   Ad Set Name                                  9637 non-null   object
 5   Ad Name                                      9637 non-null   object
 6   Country Funnel                               9637 non-null   object
 7   Geo Location Segment                         9637 non-null   object
 8   FB Spent Funnel (INR)                        9637 non-null   float64
 9   Amount Spent (INR)                           9637 non-null   float64
 10  Clicks (all)                                 9637 non-null   float64
 11  Impressions                                  9637 non-null   float64
 12  Page Likes                                   9637 non-null   float64
 13  Landing Page Views                           9637 non-null   float64
 14  Link Clicks                                  9637 non-null   float64
 15  Adds to Cart                                 9637 non-null   float64
 16  Checkouts Initiated                          9637 non-null   float64
 17  Adds of Payment Info                         9637 non-null   float64
 18  Purchases                                    9637 non-null   float64
 19  Purchases Conversion Value (INR)             9637 non-null   float64
 20  Website Contacts                             9637 non-null   float64
 21  Messaging Conversations Started              9637 non-null   float64
 22  Adds to Cart Conversion Value (INR)          9637 non-null   float64
 23  Checkouts Initiated Conversion Value (INR)   9637 non-null   float64
 24  Adds of Payment Info Conversion Value (INR)  9637 non-null   float64
 25  Row Count                                    9637 non-null   float64
 26  CTR                                          8671 non-null   float64
 27  CPM                                          9637 non-null   float64
 28  ROI                                          9637 non-null   float64
 29  CPC                                          9637 non-null   float64
dtypes: datetime64[ns](1), float64(22), object(7)
memory usage: 2.3+ MB

In [63]:
campaigns.head()

,Data Source name,Date,Campaign Name,Campaign Effective Status,Ad Set Name,Ad Name,Country Funnel,Geo Location Segment,FB Spent Funnel (INR),Amount Spent (INR),...,Website Contacts,Messaging Conversations Started,Adds to Cart Conversion Value (INR),Checkouts Initiated Conversion Value (INR),Adds of Payment Info Conversion Value (INR),Row Count,CTR,CPM,ROI,CPC
0,BRAND A,2026-01-02,UNKNOWN,PAUSED,TOF | LAL 3-5% | SALES | WOMENS,CUSTOM | VIDEO 2 | EOSS | 15TH DEC 25 – COPY,INDIA,INDIA,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0
1,BRAND A,2026-01-03,GROWIFY | 11TH JUNE | TOF | ABO | INDIA | LAL ...,PAUSED,TOF | LAL 3-5% | SALES | WOMENS,CUSTOM | VIDEO 2 | EOSS | 15TH DEC 25 – COPY,INDIA,INDIA,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0
2,UNKNOWN,2026-01-20,GROWIFY | 11TH JUNE | TOF | ABO | INDIA | LAL ...,PAUSED,UNKNOWN,UNKNOWN,INDIA,INDIA,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0
3,BRAND A,2026-01-01,GROWIFY | 11TH JUNE | TOF | ABO | INDIA | LAL ...,UNKNOWN,TOF | LAL 3-5% | SALES | WOMENS,CUSTOM | VIDEO 2 | EOSS | 15TH DEC 25 – COPY,INDIA,INDIA,0.0,0.0,...,0.0,0.0,5964500.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0
4,BRAND A,2026-01-11,GROWIFY | 11TH JUNE | TOF | ABO | INDIA | LAL ...,PAUSED,UNKNOWN,CUSTOM | VIDEO 2 | EOSS | 15TH DEC 25 – COPY,NAN,INDIA,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0

In [64]:
campaigns.describe()

C:\Users\kesha\anaconda3\Lib\site-packages\numpy\core\_methods.py:49: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

,Date,FB Spent Funnel (INR),Amount Spent (INR),Clicks (all),Impressions,Page Likes,Landing Page Views,Link Clicks,Adds to Cart,Checkouts Initiated,...,Website Contacts,Messaging Conversations Started,Adds to Cart Conversion Value (INR),Checkouts Initiated Conversion Value (INR),Adds of Payment Info Conversion Value (INR),Row Count,CTR,CPM,ROI,CPC
count,9637,9637.000000,9637.000000,9.637000e+03,9.637000e+03,9637.000000,9.637000e+03,9637.000000,9637.000000,9637.000000,...,9637.000000,9637.000000,9.637000e+03,9.637000e+03,9.637000e+03,9637.000000,8671.000000,9.637000e+03,9.637000e+03,9637.000000
mean,2026-02-09 04:06:32.985368832,5981.839204,9251.604327,1.702410e+03,9.985782e+04,0.374805,1.624892e+03,1249.898205,22.879112,1.332054,...,1.131576,5.436132,5.730898e+05,1.622586e+05,5.013301e+04,6.020650,NaN,8.805769e+03,6.970472e+02,194.436824
min,2026-01-01 00:00:00,-312112.320000,-957413.990000,-3.255600e+06,-3.639065e+06,-77.000000,-3.256500e+04,-30780.000000,-594.000000,-390.000000,...,-64.000000,-567.000000,-6.226054e+07,-1.092500e+07,-3.010700e+07,-66.000000,-inf,-4.445478e+05,-2.367692e+04,-11428.183333
25%,2026-01-19 00:00:00,4.210000,5.390000,0.000000e+00,1.000000e+01,0.000000,0.000000e+00,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,0.000300,0.000000e+00,-1.000000e+00,0.000000
50%,2026-02-06 00:00:00,242.550000,245.210000,1.600000e+01,3.420000e+02,0.000000,4.000000e+00,8.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,0.038194,2.771429e+02,-1.000000e+00,2.882430
75%,2026-03-04 00:00:00,1019.410000,1031.941569,8.000000e+01,1.833000e+03,0.000000,4.700000e+01,60.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,0.075338,1.179357e+03,-1.000000e+00,22.533750
max,2026-03-28 00:00:00,957356.160000,964131.980000,4.164600e+06,7.734387e+07,154.000000,3.795090e+06,935388.000000,7326.000000,936.000000,...,832.000000,1512.000000,1.706904e+08,1.230960e+08,5.236000e+07,132.000000,inf,1.322005e+06,6.334614e+06,95895.570000
std,NaN,38089.376286,57200.122375,6.605853e+04,1.691935e+06,6.018411,4.325170e+04,20552.311092,229.541837,18.412667,...,19.440832,55.208723,6.206682e+06,2.879127e+06,1.301065e+06,19.108435,NaN,4.992470e+04,6.453583e+04,1489.979086

In [65]:
campaigns.to_csv("cleaned_campaigns_dataset.csv", index=False)