In [2]:
import pandas as pd
import sqlite3

In [3]:
Raw = pd.read_csv("Raw_Shopify_Sales.csv")

In [4]:
Raw.head()

,Data Source name,Date,Currency,Sales Channel,Transaction Timestamp,Order Created At,Order Updated At,Order ID,Order Name,Country Funnel,...,Average Order Value (INR),New Customer Orders,Returning Customer Orders,Average Items Per Order,Discounts (INR),Row Count,SKU,Customer Sale Type,Customer ID,Shipping Country
0,Brand A,08-01-2026,INR,Online Store,2026-01-08T11:39:42Z,2026-01-08T11:39:43Z,2026-01-08T11:39:44Z,-6.318230e+12,NaN,United Arab Emirates,...,NaN,0.0,NaN,NaN,0.0,1.0,NaN,First-time,9.052170e+12,NaN
1,Brand A,NAN,INR,Online Store,2026-01-13T06:25:45Z,2026-01-13T06:25:47Z,2026-01-13T06:25:48Z,6.324090e+12,#1053,United States,...,NaN,0.0,NaN,NaN,0.0,1.0,NaN,NaN,9.965681e+14,United States
2,Brand A,19-01-2026,INR,Online Store,2026-01-19T16:16:58Z,2026-01-19T16:16:59Z,2026-01-19T16:17:00Z,6.333300e+12,#1055,United States,...,NaN,0.0,NaN,NaN,NaN,1.0,NaN,First-time,-9.979288e+14,United States
3,Brand A,29-01-2026,INR,Online Store,2026-01-29T15:56:31Z,2026-01-29T15:56:32Z,NaN,6.345630e+12,#1057,United States,...,NaN,0.0,NaN,NaN,0.0,1.0,NaN,First-time,1.000255e+15,United States
4,Brand A,21-01-2026,INR,Online Store,2026-01-21t17:02:56z,2026-01-21T17:02:59Z,2026-01-21T17:03:01Z,6.335680e+12,#1056,India,...,NaN,0.0,NaN,NaN,0.0,NaN,NaN,First-time,NaN,India

In [5]:
Raw.columns

Index(['Data Source name', 'Date', 'Currency', 'Sales Channel',
       'Transaction Timestamp', 'Order Created At', 'Order Updated At',
       'Order ID', 'Order Name', 'Country Funnel', 'Geo Location Segment',
       'Billing Country', 'Billing Province', 'Billing City', 'Order Tags',
       'Product ID', 'Product Title', 'Product Tags', 'Product Type',
       'Variant Title', 'Gross Sales (INR)', 'Net Sales (INR)',
       'Total Sales (INR)', 'Orders', 'Returns (INR)', 'Return Rate',
       'Items Sold', 'Items Returned', 'Average Order Value (INR)',
       'New Customer Orders', 'Returning Customer Orders',
       'Average Items Per Order', 'Discounts (INR)', 'Row Count', 'SKU',
       'Customer Sale Type', 'Customer ID', 'Shipping Country'],
      dtype='object')

In [6]:
Raw.info

<bound method DataFrame.info of      Data Source name         Date Currency              Sales Channel  \
0             Brand A   08-01-2026      INR               Online Store
1             Brand A          NAN      INR               Online Store
2             Brand A   19-01-2026      INR               Online Store
3             Brand A   29-01-2026      INR               Online Store
4             Brand A   21-01-2026      INR               Online Store
...               ...          ...      ...                        ...
5675          Brand A   11-03-2026      INR   magic checkout - brand a
5676          Brand A   28-03-2026      INR   magic checkout - Brand A
5677          Brand A   12-03-2026      INR   magic checkout - Brand A
5678          Brand A   28-02-2026      INR                        NaN
5679          Brand A   19-01-2026      INR   magic checkout - Brand A

      Transaction Timestamp      Order Created At      Order Updated At  \
0      2026-01-08T11:39:42Z  2026-01-08T11:39:43Z  2026-01-08T11:39:44Z
1      2026-01-13T06:25:45Z  2026-01-13T06:25:47Z  2026-01-13T06:25:48Z
2      2026-01-19T16:16:58Z  2026-01-19T16:16:59Z  2026-01-19T16:17:00Z
3      2026-01-29T15:56:31Z  2026-01-29T15:56:32Z                   NaN
4      2026-01-21t17:02:56z  2026-01-21T17:02:59Z  2026-01-21T17:03:01Z
...                     ...                   ...                   ...
5675   2026-03-11T05:40:39Z  2026-03-11T05:40:39Z  2026-03-11T05:40:55Z
5676   2026-03-28T06:01:16Z  2026-03-28T06:01:16Z  2026-03-28T06:20:15Z
5677                    NaN  2026-03-12T11:22:05Z  2026-03-12T11:22:21Z
5678   2026-02-28T07:59:03Z  2026-02-28T07:59:03Z  2026-02-28T07:59:18Z
5679   2026-01-19T11:26:32Z  2026-01-19T11:26:32Z  2026-01-19T11:26:47Z

          Order ID Order Name        Country Funnel  ...  \
0    -6.318230e+12        NaN  United Arab Emirates  ...
1     6.324090e+12      #1053         United States  ...
2     6.333300e+12      #1055         United States  ...
3     6.345630e+12      #1057         United States  ...
4     6.335680e+12      #1056                 India  ...
...            ...        ...                   ...  ...
5675  6.993820e+12     #11998                 INDIA  ...
5676  7.036970e+12        NaN                 India  ...
5677  6.996300e+12     #12023                 India  ...
5678  6.968580e+12     #11852                 India  ...
5679  6.862570e+12     #11417                 India  ...

     Average Order Value (INR) New Customer Orders Returning Customer Orders  \
0                          NaN                 0.0                       NaN
1                          NaN                 0.0                       NaN
2                          NaN                 0.0                       NaN
3                          NaN                 0.0                       NaN
4                          NaN                 0.0                       NaN
...                        ...                 ...                       ...
5675                       NaN                 NaN                       NaN
5676                       NaN                 NaN                       0.0
5677                       NaN                 NaN                       0.0
5678                       NaN                 0.0                       NaN
5679                       NaN                 NaN                       1.0

     Average Items Per Order Discounts (INR)  Row Count        SKU  \
0                        NaN             0.0        1.0        NaN
1                        NaN             0.0        1.0        NaN
2                        NaN             NaN        1.0        NaN
3                        NaN             0.0        1.0        NaN
4                        NaN             0.0        NaN        NaN
...                      ...             ...        ...        ...
5675                     NaN             0.0        1.0        NaN
5676                     NaN             0.0        NaN  JEZ-MULTI
5677                     NaN             NaN        1.0        NaN
5678                     NaN             0.0        1.0        NaN
5679                     1.0             NaN        1.0    WISH-IV

     Customer Sale Type   Customer ID Shipping Country
0            First-time  9.052170e+12              NaN
1                   NaN  9.965681e+14    United States
2            First-time -9.979288e+14    United States
3            First-time  1.000255e+15    United States
4            First-time           NaN            India
...                 ...           ...              ...
5675                NaN  9.518450e+12            India
5676          Returning  8.535520e+12            India
5677          Returning  8.621880e+12            india
5678         First-time  9.488550e+12            India
5679          Returning  8.491530e+12              NaN

[5680 rows x 38 columns]>

In [7]:
Raw.describe()

,Order ID,Product ID,Gross Sales (INR),Net Sales (INR),Total Sales (INR),Orders,Returns (INR),Return Rate,Items Sold,Items Returned,Average Order Value (INR),New Customer Orders,Returning Customer Orders,Average Items Per Order,Discounts (INR),Row Count,Customer ID
count,5.230000e+03,3.142000e+03,5.221000e+03,5.223000e+03,5.224000e+03,5219.000000,5203.000000,3211.0,5089.000000,283.000000,2.265000e+03,3740.000000,1647.000000,2277.000000,5216.000000,5223.000000,5.216000e+03
mean,1.043430e+14,9.611715e+13,1.877585e+05,1.591300e+05,1.735468e+05,6.597624,474.298674,0.0,4.115347,5.452297,3.700757e+05,4.963102,2.446873,16.340360,960.149168,10.729083,1.216040e+14
std,2.936214e+14,2.485013e+14,1.338874e+06,1.143849e+06,1.193564e+06,31.019736,11398.963653,0.0,15.000061,25.491627,1.904761e+06,20.436628,10.586079,43.182834,13296.100813,28.848744,3.292952e+14
min,-9.262486e+14,-7.951593e+14,-2.013000e+07,-1.016500e+07,-9.280000e+06,-144.000000,-95000.000000,0.0,-55.000000,-113.000000,-1.624000e+07,-90.000000,-53.000000,-130.000000,-57761.070885,-87.000000,-1.051554e+15
25%,6.849580e+12,7.873492e+12,0.000000e+00,0.000000e+00,1.500000e+02,0.000000,0.000000,0.0,0.000000,0.000000,6.560000e+03,0.000000,0.000000,1.000000,0.000000,1.000000,8.872688e+12
50%,6.951000e+12,8.357400e+12,6.080000e+03,5.520000e+03,6.800000e+03,0.000000,0.000000,0.0,1.000000,0.000000,8.280000e+03,0.000000,0.000000,1.000000,0.000000,1.000000,9.306370e+12
75%,7.010970e+12,8.550100e+12,9.120000e+03,9.000000e+03,1.040000e+04,1.000000,0.000000,0.0,1.000000,1.000000,5.560000e+04,1.000000,1.000000,1.000000,0.000000,1.000000,9.489250e+12
max,9.290166e+14,8.276442e+14,2.281400e+07,2.000900e+07,2.169200e+07,144.000000,432000.000000,0.0,275.000000,113.000000,2.030000e+07,90.000000,53.000000,260.000000,361026.000000,174.000000,1.054464e+15

In [8]:
Raw.duplicated().sum()

21

In [11]:
# Convert timestamps to datetime objects
Raw['Transaction Timestamp'] = pd.to_datetime(Raw['Transaction Timestamp'], errors='coerce')
Raw['Order Created At'] = pd.to_datetime(Raw['Order Created At'], errors='coerce')

# Fill missing 'Date' values using the date part of 'Transaction Timestamp'
Raw['Date'] = pd.to_datetime(Raw['Date'], errors='coerce')
Raw['Date'] = Raw['Date'].fillna(Raw['Transaction Timestamp'].dt.date)
Raw['Date'] = Raw['Date'].fillna(Raw['Order Created At'].dt.date)

# Ensure 'Date' is in a standard YYYY-MM-DD format
Raw['Date'] = pd.to_datetime(Raw['Date']).dt.date

In [14]:
# List of categorical columns to clean
import numpy as np
cat_cols = ['Sales Channel', 'Billing Country', 'Billing City', 'Product Type', 'Shipping Country']

for col in cat_cols:
    # Replace literal 'NAN' or 'nan' strings with actual Nulls
    Raw[col] = Raw[col].replace(['NAN', 'nan', 'NaN'], np.nan)
    
    # Standardize casing (Title Case for consistency)
    Raw[col] = Raw[col].astype(str).str.title().str.strip()
    
    # Re-mask the 'Nan' string back to a real null if it was created by the .str.title()
    Raw[col] = Raw[col].replace('Nan', np.nan)

In [15]:
# Fix Order ID: Convert from scientific notation to string
Raw['Order ID'] = Raw['Order ID'].apply(lambda x: '{:.0f}'.format(x) if pd.notnull(x) else x)

# Ensure numeric columns are floats
numeric_cols = ['Gross Sales (INR)', 'Net Sales (INR)', 'Discounts (INR)', 'Returns (INR)']
for col in numeric_cols:
    Raw[col] = pd.to_numeric(Raw[col], errors='coerce').fillna(0.0)

# Recalculate Net Sales to ensure accuracy
# Net Sales = Gross Sales - Discounts - Returns
Raw['Net Sales (INR)'] = Raw['Gross Sales (INR)'] - Raw['Discounts (INR)'] - abs(Raw['Returns (INR)'])

# Calculate Return Rate if missing
Raw['Return Rate'] = Raw.apply(lambda row: (row['Items Returned'] / row['Items Sold']) 
                             if row['Items Sold'] > 0 else 0, axis=1)

In [16]:
def generate_quality_report(Raw):
    report = {
        "Total Rows": len(Raw),
        "Missing Dates Fixed": Raw['Date'].notnull().sum(),
        "Unique Sales Channels": Raw['Sales Channel'].nunique(),
        "Total Net Sales (INR)": Raw['Net Sales (INR)'].sum()
    }
    print("--- DATA QUALITY REPORT ---")
    for key, value in report.items():
        print(f"{key}: {value}")

generate_quality_report(Raw)

# Export the cleaned data for Task 2 (SQL)
Raw.to_csv('Cleaned_Shopify_Sales.csv', index=False)

--- DATA QUALITY REPORT ---
Total Rows: 5680
Missing Dates Fixed: 5639
Unique Sales Channels: 4
Total Net Sales (INR): 972412067.845676